name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest flake8 black mypy
    
    - name: Lint with flake8
      run: |
        flake8 src/ --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 src/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Check code formatting with black
      run: |
        black --check src/
    
    - name: Type checking with mypy
      run: |
        mypy src/ --ignore-missing-imports || true
    
    - name: Run unit tests
      run: |
        pytest tests/ -v --tb=short

  docker-build:
    runs-on: ubuntu-latest
    needs: lint-and-test
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Docker image (CPU)
      run: |
        docker build -f docker/Dockerfile.cpu -t plate-detector:cpu-latest .
    
    - name: Test Docker image
      run: |
        docker run plate-detector:cpu-latest python --version

  # Optional: GPU testing (requires self-hosted runner with GPU)
  # gpu-test:
  #   runs-on: self-hosted
  #   needs: lint-and-test
  #   
  #   steps:
  #   - uses: actions/checkout@v3
  #   
  #   - name: Run inference test on GPU
  #     run: |
  #       python src/run_demo.py --weights models/best.pt --source test_data/sample.jpg
